substitutions:
  source_sensor_resistance: 3.3kOhm

packages:
  TEMP_1_BLE: !include "TEMP-1_BLE.yaml"

esphome:
  name: "apollo-temp-1ble-r2"
  project:
    name: "Apollo.TEMP-1BLE_R2"
    version: "${version}"

dashboard_import:
  package_import_url: github://ApolloAutomation/TEMP-1/Integrations/ESPHome/TEMP-1_BLE_R2.yaml
  import_full_config: false
