substitutions:
  source_sensor_resistance: 3.3kOhm
  firmware_update_manifest_url: https://apolloautomation.github.io/TEMP-1/firmware2/manifest.json

packages:
  TEMP_1: !include "TEMP-1.yaml"

esphome:
  name: "apollo-temp-1-r2"
  project:
    name: "Apollo.TEMP-1_R2"
    version: "${version}"

dashboard_import:
  package_import_url: github://ApolloAutomation/TEMP-1/Integrations/ESPHome/TEMP-1_Minimal_R2.yaml
  import_full_config: false
  
