substitutions:
  source_sensor_resistance: 3.3kOhm

packages:
  TEMP_1_Minimal: !include "TEMP-1_Minimal.yaml"

esphome:
  name: "apollo-temp-1-minimalr2"
  project:
    name: "Apollo.TEMP-1_Minimal_R2"
    version: "${version}"

dashboard_import:
  package_import_url: github://ApolloAutomation/TEMP-1/Integrations/ESPHome/TEMP-1_Minimal_R2.yaml
  import_full_config: false
