substitutions:
  source_sensor_resistance: 3.3kOhm

packages:
  TEMP_1B_BLE: !include "TEMP-1B_BLE.yaml"

esphome:
  name: "apollo-temp-1bble-r2"
  project:
    name: "Apollo.TEMP-1BBLE_R2"
    version: "${version}"

dashboard_import:
  package_import_url: github://ApolloAutomation/TEMP-1/Integrations/ESPHome/TEMP-1B_BLE_R2.yaml
  import_full_config: false
