esphome:
  name: "${name}"
  friendly_name: Apollo TEMP-1
  comment: Apollo TEMP-1
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ApolloAutomation.TEMP-1"
    version: "${version}"

  min_version: 2024.2.0
  on_boot:
    priority: 500
    then:
      - switch.turn_on: accessory_power
      
  on_shutdown:
    - switch.turn_off: accessory_power


dashboard_import:
  package_import_url: github://ApolloAutomation/TEMP-1/Integrations/ESPHome/TEMP-1_Minimal.yaml
  import_full_config: false

ota:
  - platform: esphome
wifi:
  ap:
    ssid: "Apollo TEMP1 Hotspot"

packages:
  remote_package:
    url: https://github.com/ApolloAutomation/TEMP-1/
    ref: main
    files:
      - Integrations/ESPHome/Core.yaml
    refresh: 0d
