substitutions:
  source_sensor_resistance: 3.3kOhm
  variant_slug: "-b2"

packages:
  TEMP_1B: !include "TEMP-1B.yaml"

esphome:
  name: "apollo-temp-1b-42"
  project:
    name: "Apollo.TEMP-1B_R2"
    version: "${version}"

dashboard_import:
  package_import_url: github://ApolloAutomation/TEMP-1/Integrations/ESPHome/TEMP-1B_Minimal_R2.yaml
  import_full_config: false
