name: Weekly Firmware Build

on:
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

jobs:
  build:
    name: Weekly Build
    uses: ApolloAutomation/Workflows/.github/workflows/esphome-ci.yml@main
    with:
      yaml-files: |
        Integrations/ESPHome/TEMP-1.yaml
        Integrations/ESPHome/TEMP-1_BLE.yaml
        Integrations/ESPHome/TEMP-1B.yaml
        Integrations/ESPHome/TEMP-1B_BLE.yaml
        Integrations/ESPHome/TEMP-1_Minimal.yaml
        Integrations/ESPHome/TEMP-1B_Minimal.yaml
        Integrations/ESPHome/TEMP-1_R2.yaml
        Integrations/ESPHome/TEMP-1_BLE_R2.yaml
        Integrations/ESPHome/TEMP-1B_R2.yaml
        Integrations/ESPHome/TEMP-1B_BLE_R2.yaml
        Integrations/ESPHome/TEMP-1_Minimal_R2.yaml
        Integrations/ESPHome/TEMP-1B_Minimal_R2.yaml

